// ChefOne — Pantry Manager Mock Data

export const initialPantryItems = [
  {
    id: 1,
    name: "Chicken Breast",
    category: "Proteins",
    quantity: 4,
    unit: "pieces",
    expiry: "2026-05-15",
  },
  {
    id: 2,
    name: "Cherry Tomatoes",
    category: "Vegetables",
    quantity: 250,
    unit: "g",
    expiry: "2026-05-13",
  },
  {
    id: 3,
    name: "Heavy Cream",
    category: "Dairy",
    quantity: 500,
    unit: "ml",
    expiry: "2026-05-18",
  },
  {
    id: 4,
    name: "Parmesan Cheese",
    category: "Dairy",
    quantity: 150,
    unit: "g",
    expiry: "2026-05-25",
  },
  {
    id: 5,
    name: "Spaghetti",
    category: "Grains",
    quantity: 500,
    unit: "g",
    expiry: "2027-01-01",
  },
  {
    id: 6,
    name: "Olive Oil",
    category: "Oils & Condiments",
    quantity: 750,
    unit: "ml",
    expiry: "2027-03-01",
  },
  {
    id: 7,
    name: "Garlic",
    category: "Vegetables",
    quantity: 1,
    unit: "bulb",
    expiry: "2026-06-01",
  },
  {
    id: 8,
    name: "Spinach",
    category: "Vegetables",
    quantity: 200,
    unit: "g",
    expiry: "2026-05-12",
  },
  {
    id: 9,
    name: "Eggs",
    category: "Proteins",
    quantity: 12,
    unit: "pieces",
    expiry: "2026-05-20",
  },
  {
    id: 10,
    name: "Basmati Rice",
    category: "Grains",
    quantity: 1,
    unit: "kg",
    expiry: "2027-06-01",
  },
  {
    id: 11,
    name: "Butter",
    category: "Dairy",
    quantity: 250,
    unit: "g",
    expiry: "2026-05-30",
  },
  {
    id: 12,
    name: "Lemon",
    category: "Fruits",
    quantity: 3,
    unit: "pieces",
    expiry: "2026-05-16",
  },
];

export const categories = [
  "All",
  "Proteins",
  "Vegetables",
  "Fruits",
  "Dairy",
  "Grains",
  "Oils & Condiments",
  "Spices",
  "Other",
];

export const units = [
  "g",
  "kg",
  "ml",
  "L",
  "pieces",
  "cups",
  "tbsp",
  "tsp",
  "bulb",
  "bunch",
  "can",
  "box",
];
