/**
 * VietnameseMealResultCard — Displays a complete Vietnamese multi-dish meal
 * generated by AI. Shows all dishes in a grid with individual save buttons.
 */
import React, { useState } from "react";
import Card from "components/card";
import {
  MdOutlineTimer,
  MdOutlineLocalFireDepartment,
  MdOutlinePeople,
  MdOutlineBookmark,
  MdOutlineCheck,
  MdOutlineCalendarMonth,
} from "react-icons/md";

const VietnameseMealResultCard = ({ meal, onSaveDish, onSaveAll, onAddToMealPlan }) => {
  const [savedDishes, setSavedDishes] = useState(new Set());
  const [allSaved, setAllSaved] = useState(false);

  if (!meal || !meal.dishes) return null;

  const handleSaveDish = (dish, idx) => {
    if (onSaveDish) onSaveDish(dish);
    setSavedDishes((prev) => new Set([...prev, idx]));
  };

  const handleSaveAll = () => {
    if (onSaveAll) onSaveAll(meal);
    setAllSaved(true);
    const allIdxs = meal.dishes.map((_, idx) => idx);
    setSavedDishes(new Set(allIdxs));
    setTimeout(() => setAllSaved(false), 3000);
  };

  const totalNutrition = meal.totalNutrition || meal.dishes.reduce(
    (tot, d) => ({
      calories: tot.calories + (d.calories || 0),
      protein: tot.protein + (d.protein || 0),
      carbs: tot.carbs + (d.carbs || 0),
      fat: tot.fat + (d.fat || 0),
    }),
    { calories: 0, protein: 0, carbs: 0, fat: 0 }
  );

  return (
    <Card extra="p-6">
      {/* Header */}
      <div className="mb-5 border-b border-gray-100 pb-4 dark:border-white/10">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <div className="mb-1 flex items-center gap-2">
              <span className="text-2xl">🍲</span>
              <h2 className="text-2xl font-bold text-navy-700 dark:text-white">
                {meal.mealName || "Mâm Cơm Việt"}
              </h2>
            </div>
            {meal.description && (
              <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                {meal.description}
              </p>
            )}
            <div className="mt-2 flex items-center gap-2">
              <span className="rounded-full bg-green-50 px-3 py-0.5 text-xs font-semibold text-green-600">
                🇻🇳 Vietnamese Multi-Dish Meal
              </span>
              <span className="rounded-full bg-brand-50 px-3 py-0.5 text-xs font-semibold text-brand-600">
                {meal.dishes.length} dishes
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Total Nutrition Summary */}
      <div className="mb-5 grid grid-cols-4 gap-3">
        {[
          { label: "Total Calories", value: `${totalNutrition.calories}`, unit: "kcal", color: "bg-red-50 dark:bg-red-900/20" },
          { label: "Total Protein", value: `${totalNutrition.protein}`, unit: "g", color: "bg-brand-50 dark:bg-brand-900/20" },
          { label: "Total Carbs", value: `${totalNutrition.carbs}`, unit: "g", color: "bg-amber-50 dark:bg-amber-900/20" },
          { label: "Total Fat", value: `${totalNutrition.fat}`, unit: "g", color: "bg-green-50 dark:bg-green-900/20" },
        ].map((m) => (
          <div key={m.label} className={`flex flex-col items-center rounded-xl p-3 ${m.color}`}>
            <span className="text-lg font-bold text-navy-700 dark:text-white">
              {m.value}<span className="text-xs font-medium">{m.unit}</span>
            </span>
            <span className="text-xs text-gray-600 dark:text-gray-400">{m.label}</span>
          </div>
        ))}
      </div>

      {/* Dish Cards Grid */}
      <div className="mb-5">
        <h3 className="mb-3 text-sm font-bold uppercase tracking-wide text-gray-600 dark:text-gray-400">
          Dishes in this Meal
        </h3>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {meal.dishes.map((dish, idx) => (
            <div
              key={idx}
              className="rounded-2xl border border-gray-100 bg-white p-4 transition hover:shadow-md dark:border-white/10 dark:bg-navy-700"
            >
              {/* Dish Header */}
              <div className="mb-2 flex items-start justify-between gap-2">
                <h4 className="text-base font-bold text-navy-700 dark:text-white">
                  {dish.name}
                </h4>
                <button
                  onClick={() => handleSaveDish(dish, idx)}
                  disabled={savedDishes.has(idx)}
                  className={`flex-shrink-0 flex items-center gap-1 rounded-lg px-2 py-1 text-xs font-semibold transition ${
                    savedDishes.has(idx)
                      ? "bg-green-500 text-white"
                      : "bg-brand-50 text-brand-600 hover:bg-brand-100"
                  }`}
                >
                  {savedDishes.has(idx) ? (
                    <><MdOutlineCheck className="h-3 w-3" /> Saved</>
                  ) : (
                    <><MdOutlineBookmark className="h-3 w-3" /> Save</>
                  )}
                </button>
              </div>

              {/* Description */}
              {dish.description && (
                <p className="mb-2 text-xs text-gray-500 dark:text-gray-400">
                  {dish.description}
                </p>
              )}

              {/* Mini Nutrition */}
              <div className="mb-3 flex flex-wrap gap-2 text-xs text-gray-500">
                <span className="flex items-center gap-0.5">
                  <MdOutlineLocalFireDepartment className="h-3 w-3 text-red-400" />
                  {dish.calories} kcal
                </span>
                <span>P: {dish.protein}g</span>
                <span>C: {dish.carbs}g</span>
                <span>F: {dish.fat}g</span>
              </div>

              {/* Meta */}
              <div className="mb-3 flex flex-wrap gap-2 text-xs text-gray-500">
                {dish.prepTime && (
                  <span className="flex items-center gap-0.5">
                    <MdOutlineTimer className="h-3 w-3" /> Prep: {dish.prepTime}
                  </span>
                )}
                {dish.cookTime && (
                  <span className="flex items-center gap-0.5">
                    <MdOutlineTimer className="h-3 w-3 text-orange-400" /> Cook: {dish.cookTime}
                  </span>
                )}
                {dish.servings && (
                  <span className="flex items-center gap-0.5">
                    <MdOutlinePeople className="h-3 w-3 text-blue-400" /> {dish.servings} servings
                  </span>
                )}
              </div>

              {/* Ingredients */}
              {dish.ingredients && dish.ingredients.length > 0 && (
                <div className="mb-2">
                  <p className="mb-1 text-[10px] font-bold uppercase tracking-wide text-gray-400">
                    Ingredients
                  </p>
                  <div className="flex flex-wrap gap-1">
                    {dish.ingredients.slice(0, 5).map((ing, i) => (
                      <span
                        key={i}
                        className="rounded-full bg-gray-100 px-2 py-0.5 text-[10px] text-gray-600 dark:bg-navy-600 dark:text-gray-400"
                      >
                        {ing.name}
                      </span>
                    ))}
                    {dish.ingredients.length > 5 && (
                      <span className="rounded-full bg-gray-100 px-2 py-0.5 text-[10px] text-gray-400">
                        +{dish.ingredients.length - 5} more
                      </span>
                    )}
                  </div>
                </div>
              )}

              {/* Tags */}
              {dish.tags && dish.tags.length > 0 && (
                <div className="flex flex-wrap gap-1">
                  {dish.tags.map((tag) => (
                    <span
                      key={tag}
                      className="rounded-full bg-brand-50 px-2 py-0.5 text-[10px] font-medium text-brand-500"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-3 border-t border-gray-100 pt-4 dark:border-white/10">
        <button
          onClick={handleSaveAll}
          disabled={allSaved}
          className={`flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-semibold transition ${
            allSaved
              ? "bg-green-500 text-white"
              : "bg-brand-500 text-white hover:bg-brand-600"
          }`}
        >
          {allSaved ? (
            <><MdOutlineCheck className="h-4 w-4" /> All Saved!</>
          ) : (
            <><MdOutlineBookmark className="h-4 w-4" /> Save All to My Recipes</>
          )}
        </button>
        {onAddToMealPlan && (
          <button
            onClick={() => onAddToMealPlan(meal)}
            className="flex items-center gap-2 rounded-xl bg-green-500 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-green-600"
          >
            <MdOutlineCalendarMonth className="h-4 w-4" />
            Add to Meal Plan
          </button>
        )}
      </div>
    </Card>
  );
};

export default VietnameseMealResultCard;